name: 'tag-ur-it'
description: 'Label and assign issues based on their contents'
author: 'damccorm'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
runs:
  using: 'node12'
  main: 'lib/index.js'
